apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
  selector:
    app: podinfo